/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package novoselac.view;

import java.awt.BorderLayout;
import novoselac.controller.ObradaDjelatnik;
import novoselac.controller.ObradaPosjeta;
import novoselac.model.GrafPodaci;
import novoselac.util.Aplikacija;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Administrator
 */
public class PregledPosjetaPoDjelatnikuGraf 
        extends javax.swing.JFrame
implements NovoselacViewSucelje{
    
    private ObradaPosjeta obrada;
    private ObradaDjelatnik obradaDjelatnik;

    /**
     * Creates new form PregledPosjetaPoDjelatnikuGraf
     */
    public PregledPosjetaPoDjelatnikuGraf() {
        initComponents();
        obrada= new ObradaPosjeta();
        obradaDjelatnik= new ObradaDjelatnik();
        
        setTitle(Aplikacija.NAZIV_NOVOSELAC+ ": "+
               Aplikacija.OPERATER.getImePrezime() +
                ": Pregled broja posjeta po djelatnicima");
        definirajGrafDjelatnik();
    }

    private void definirajGrafDjelatnik(){
        
         DefaultPieDataset dataset = new DefaultPieDataset( );
         
         for(GrafPodaci gp : new ObradaDjelatnik().getGrafPodaci()){
            
             dataset.setValue(gp.getNaziv() + " (" + gp.getBroj() + ")", 
                     Double.valueOf(gp.getBroj()));
      }
         
         JFreeChart chart = ChartFactory.createPieChart(
         "Statistika posjeta po djelatnicima",   // naslov grafa
         dataset,          
         true,              
         false, 
         false);
          
          ChartPanel cp = new ChartPanel(chart);
          
          pnlGrafDjelatnik.setLayout(new BorderLayout());
          pnlGrafDjelatnik.add(cp,BorderLayout.CENTER);
          pnlGrafDjelatnik.validate();
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGrafDjelatnik = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlGrafDjelatnikLayout = new javax.swing.GroupLayout(pnlGrafDjelatnik);
        pnlGrafDjelatnik.setLayout(pnlGrafDjelatnikLayout);
        pnlGrafDjelatnikLayout.setHorizontalGroup(
            pnlGrafDjelatnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1018, Short.MAX_VALUE)
        );
        pnlGrafDjelatnikLayout.setVerticalGroup(
            pnlGrafDjelatnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlGrafDjelatnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlGrafDjelatnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlGrafDjelatnik;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ucitaj() {
    }

    @Override
    public void napuniView() {
   }

    @Override
    public void napuniModel() {
    }
}
