/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package novoselac.view;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import novoselac.controller.ObradaDjelatnik;
import novoselac.controller.ObradaPosjeta;
import novoselac.model.Dijete;
import novoselac.model.Djelatnik;
import novoselac.model.Posjeta;
import novoselac.util.Aplikacija;

/**
 *
 * @author Administrator
 */
public class ProzorPregledPosjetaNaDjelatniku 
        extends javax.swing.JFrame 
        implements NovoselacViewSucelje{
    
    private ObradaPosjeta obrada;
    private ObradaDjelatnik obradaDjelatnik;
//     private DecimalFormat df;

    /**
     * Creates new form ProzorPregledPosjetaNaDjelatniku
     */
    public ProzorPregledPosjetaNaDjelatniku() {
        initComponents();
        obrada= new ObradaPosjeta();
        obradaDjelatnik = new ObradaDjelatnik();
//         DecimalFormatSymbols dfs=
//                new DecimalFormatSymbols(
//                        new Locale("hr", "HR"));
//        df= new DecimalFormat("###,##0.00", dfs);
        
         setTitle(Aplikacija.NAZIV_NOVOSELAC+ ": "+
               Aplikacija.OPERATER.getImePrezime() +
                ": Posjete na djelatniku");
        ucitajFilterDjelatnici();
//         ucitajDjelatnike();
//         ucitajPosjete();
         ucitaj();
    }
    
  private void ucitajFilterDjelatnici(){
      DefaultComboBoxModel<Djelatnik> m
              = new DefaultComboBoxModel<>();
      m.addAll(new ObradaDjelatnik().read());
      cmbFilterDjelatnici.setModel(m);
      cmbFilterDjelatnici.repaint();
      cmbFilterDjelatnici.setSelectedIndex(0);
  }
    
    
    
    
//private void ucitajDjelatnike(){
//          DefaultComboBoxModel<Djelatnik> m
//                = new DefaultComboBoxModel<>();
//          Djelatnik d= new Djelatnik();
//          d.setIme(ime);
//        m.addAll(new ObradaDjelatnik().read());
//        cmbFilterDjelatnici.setModel(m);
//        cmbFilterDjelatnici.repaint();
//         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstDogovorenePosjete = new javax.swing.JList<>();
        cmbFilterDjelatnici = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstDogovorenePosjete.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDogovorenePosjeteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstDogovorenePosjete);

        cmbFilterDjelatnici.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilterDjelatniciItemStateChanged(evt);
            }
        });

        jLabel14.setText("Djelatnik");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFilterDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addComponent(cmbFilterDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFilterDjelatniciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilterDjelatniciItemStateChanged
        ucitaj();
    }//GEN-LAST:event_cmbFilterDjelatniciItemStateChanged

    private void lstDogovorenePosjeteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDogovorenePosjeteValueChanged
         if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstDogovorenePosjete.getSelectedValue()==null){
            return;
        }

        obrada.setEntitet(lstDogovorenePosjete.getSelectedValue());

        napuniView();
    }//GEN-LAST:event_lstDogovorenePosjeteValueChanged

    @Override
    
    //veza posjete i djelatnika
    //read treba primiti filter djelatnika --tu puca nešto ne valja
    public void ucitaj() {
            
       DefaultListModel<Posjeta> m = new DefaultListModel<>();
       m.addAll( obrada.read((Djelatnik)cmbFilterDjelatnici.getSelectedItem()
        ));
       lstDogovorenePosjete.setModel(m);
       lstDogovorenePosjete.repaint();
    }

    @Override
    public void napuniView() {
        var e = obrada.getEntitet();
        cmbFilterDjelatnici.setSelectedItem(e.getDjelatnik());
   }

    @Override
    public void napuniModel() {
         var e = obrada.getEntitet();
         e.setDjelatnik((Djelatnik) cmbFilterDjelatnici.getSelectedItem());
   }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Djelatnik> cmbFilterDjelatnici;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Posjeta> lstDogovorenePosjete;
    // End of variables declaration//GEN-END:variables
}
