/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package novoselac.view;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import novoselac.controller.ObradaDjelatnik;
import novoselac.controller.ObradaPosjeta;
import novoselac.model.Djelatnik;
import novoselac.model.Posjeta;
import novoselac.util.Aplikacija;
import novoselac.util.NovoselacException;

/**
 *
 * @author Administrator
 */
public class ProzorRasporedZaposlenih 
        extends javax.swing.JFrame
implements NovoselacViewSucelje{

    private ObradaDjelatnik obrada;
    private ObradaPosjeta obradaPosjeta;
    
    /**
     * Creates new form ProzorRasporedZaposlenih
     */
    public ProzorRasporedZaposlenih() {
        initComponents();
        obrada = new ObradaDjelatnik();
        obradaPosjeta = new ObradaPosjeta();
        
        setTitle(Aplikacija.NAZIV_NOVOSELAC + ": " + 
                Aplikacija.OPERATER.getImePrezime() + 
                ": Raspored");
        
        ucitajDjelatnike();
//        ucitajPosjete();
        ucitaj();
        
        
          
        
        
    }
    
      private void ucitajDjelatnike(){
          DefaultComboBoxModel<Djelatnik> m
                = new DefaultComboBoxModel<>();
        m.addAll(new ObradaDjelatnik().read());
        cmbFilterDjelatnici.setModel(m);
        cmbFilterDjelatnici.repaint();
        cmbFilterDjelatnici.setSelectedIndex(0);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUvjet = new javax.swing.JTextField();
        btnTrazi = new javax.swing.JButton();
        btnDodajPosjetu = new javax.swing.JButton();
        btnObrisiPosjetu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDogovorenePosjete = new javax.swing.JList<>();
        cmbFilterDjelatnici = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPosjeteNaDjelatniku = new javax.swing.JList<>();
        btnNoviUnos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setText("Dodjela podjete djelatniku ");

        jLabel13.setText("Dogovorene posjete");

        txtUvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUvjetKeyPressed(evt);
            }
        });

        btnTrazi.setText("🔍");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        btnDodajPosjetu.setText("<<");
        btnDodajPosjetu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPosjetuActionPerformed(evt);
            }
        });

        btnObrisiPosjetu.setText(">>");
        btnObrisiPosjetu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPosjetuActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstDogovorenePosjete);

        cmbFilterDjelatnici.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilterDjelatniciItemStateChanged(evt);
            }
        });

        jLabel14.setText("Djelatnik");

        btnDodaj.setText("Potvrdi unos");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lstPosjeteNaDjelatniku);

        btnNoviUnos.setText("Unos novog djelatnika");
        btnNoviUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviUnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDodajPosjetu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObrisiPosjetu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtUvjet)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbFilterDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnNoviUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbFilterDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNoviUnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrazi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnDodajPosjetu)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiPosjetu))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnDodaj)))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUvjetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            ucitajPosjete();
        }
    }//GEN-LAST:event_txtUvjetKeyPressed

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
//        ucitajPosjete();
    }//GEN-LAST:event_btnTraziActionPerformed

    private void btnDodajPosjetuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPosjetuActionPerformed

//        if(lstDogovorenePosjete.getSelectedValuesList()==null
//            || lstDogovorenePosjete.getSelectedValuesList().isEmpty()){
//            JOptionPane.showMessageDialog(getRootPane(),
//                "Prvo pronađite posjetu");
//            return;
//        }
//
//        if(lstPosjeteDjelatnik.getModel()==null ||
//            !(lstPosjeteDjelatnik.getModel() instanceof DefaultListModel<Posjeta>)){
//            lstPosjeteDjelatnik.setModel(new DefaultListModel<Posjeta>());
//        }
//
//        DefaultListModel<Posjeta> m =
//        (DefaultListModel<Posjeta>) lstPosjeteDjelatnik.getModel();
//
//        DefaultListModel<Posjeta> polaznici =
//        (DefaultListModel<Posjeta>) lstPosjeteDjelatnik.getModel();
//        boolean postoji;
//        for(Posjeta pub : lstDogovorenePosjete.getSelectedValuesList()){
//            postoji=false;
//            for(int i=0;i<polaznici.getSize();i++){
//                if(pub.getSifra()==polaznici.get(i).getSifra()){
//                    postoji=true;
//                    break;
//                }
//            }
//            if(!postoji){
//                polaznici.addElement(pub);
//            }
//        }
//        lstPosjeteDjelatnik.repaint();
//
    }//GEN-LAST:event_btnDodajPosjetuActionPerformed

    private void btnObrisiPosjetuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPosjetuActionPerformed
//        if(lstPosjeteDjelatnik.getSelectedValuesList()==null
//            || lstPosjeteDjelatnik.getSelectedValuesList().isEmpty()){
//            JOptionPane.showMessageDialog(getRootPane(),
//                "Prvo odaberite polaznike u grupi");
//            return;
//        }
//
//        DefaultListModel<Posjeta> m =
//        (DefaultListModel<Posjeta>) lstPosjeteDjelatnik.getModel();
//
//        for(Posjeta p : lstPosjeteDjelatnik.getSelectedValuesList()){
//            m.removeElement(p);
//        }
//        lstPosjeteDjelatnik.repaint();

    }//GEN-LAST:event_btnObrisiPosjetuActionPerformed

    private void cmbFilterDjelatniciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilterDjelatniciItemStateChanged
        ucitaj();
    }//GEN-LAST:event_cmbFilterDjelatniciItemStateChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        obrada.setEntitet(new Djelatnik());
        napuniModel();
        try {
            obrada.create();
        } catch (NovoselacException ex) {
            Logger.getLogger(ProzorRasporedZaposlenih.class.getName()).log(Level.SEVERE, null, ex);
        }
        ucitaj();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnNoviUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviUnosActionPerformed
        new ProzorDjelatnik().setVisible(true);
    }//GEN-LAST:event_btnNoviUnosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajPosjetu;
    private javax.swing.JButton btnNoviUnos;
    private javax.swing.JButton btnObrisiPosjetu;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JComboBox<Djelatnik> cmbFilterDjelatnici;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Posjeta> lstDogovorenePosjete;
    private javax.swing.JList<Posjeta> lstPosjeteNaDjelatniku;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ucitaj() {
    }

    @Override
    public void napuniView() {
   }

    @Override
    public void napuniModel() {
    }
}
