/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package novoselac.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import novoselac.controller.ObradaDjelatnik;
import novoselac.controller.ObradaPosjeta;
import novoselac.model.Djelatnik;
import novoselac.model.Posjeta;
import novoselac.util.Aplikacija;
import novoselac.util.NovoselacException;

/**
 *
 * @author Administrator
 */
public class ProzorRasporedZaposlenih 
        extends javax.swing.JFrame
implements NovoselacViewSucelje{

    private ObradaDjelatnik obradaDjelatnik;
    private ObradaPosjeta obradaPosjeta;
    
    /**
     * Creates new form ProzorRasporedZaposlenih
     */
    public ProzorRasporedZaposlenih() {
        initComponents();
        obradaDjelatnik = new ObradaDjelatnik();
        obradaPosjeta = new ObradaPosjeta();
        
        setTitle(Aplikacija.NAZIV_NOVOSELAC + ": " + 
                Aplikacija.OPERATER.getImePrezime() + 
                ": Raspored");
        
   
    ucitajDjelatnike();
    ucitajPosjete();
    ucitaj();
        
        
          
        
        
    }
    
    
      
    
      private void ucitajDjelatnike(){
          DefaultComboBoxModel<Djelatnik> m
                = new DefaultComboBoxModel<>();
        m.addAll(new ObradaDjelatnik().read());
        cmbFilterDjelatnici.setModel(m);
        cmbFilterDjelatnici.repaint();
         }

      private void ucitajPosjete(){
           DefaultListModel<Posjeta> m = new DefaultListModel<>();
        m.addAll(obradaPosjeta.read(txtUvjet.getText().trim()));
       lstDogovorenePosjete.setModel(m);
       lstDogovorenePosjete.repaint();
      }
      @Override
    public void ucitaj() {
//          DefaultListModel<Posjeta> m= new DefaultListModel<>();
//        m.addAll(obradaPosjeta.read(txtUvjet.getText().trim()));
//        lstPosjeteNaDjelatniku.setModel(m);
//        lstPosjeteNaDjelatniku.repaint();
        
      
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUvjet = new javax.swing.JTextField();
        btnTrazi = new javax.swing.JButton();
        btnDodajPosjetu = new javax.swing.JButton();
        btnObrisiPosjetu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDogovorenePosjete = new javax.swing.JList<>();
        cmbFilterDjelatnici = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPosjeteNaDjelatniku = new javax.swing.JList<>();
        btnPregledPosjetaNaDjelatniku = new javax.swing.JButton();
        btnNoviUnos1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel12.setText("Dodjela podjete djelatniku ");

        jLabel13.setText("Dogovorene posjete");

        txtUvjet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUvjetKeyPressed(evt);
            }
        });

        btnTrazi.setText("🔍");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        btnDodajPosjetu.setText("<<");
        btnDodajPosjetu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajPosjetuActionPerformed(evt);
            }
        });

        btnObrisiPosjetu.setText(">>");
        btnObrisiPosjetu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiPosjetuActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstDogovorenePosjete);

        cmbFilterDjelatnici.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilterDjelatniciItemStateChanged(evt);
            }
        });

        jLabel14.setText("Djelatnik");

        btnDodaj.setText("Potvrdi unos");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lstPosjeteNaDjelatniku);

        btnPregledPosjetaNaDjelatniku.setText("Ispis posjeta po djelaniku");
        btnPregledPosjetaNaDjelatniku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledPosjetaNaDjelatnikuActionPerformed(evt);
            }
        });

        btnNoviUnos1.setText("Unos novog djelatnika");
        btnNoviUnos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviUnos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cmbFilterDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnNoviUnos1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnPregledPosjetaNaDjelatniku, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56))
                                    .addComponent(jScrollPane3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(116, 116, 116)
                                                .addComponent(txtUvjet)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addComponent(btnTrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnDodajPosjetu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnObrisiPosjetu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFilterDjelatnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNoviUnos1)
                    .addComponent(btnPregledPosjetaNaDjelatniku))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodaj)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTrazi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodajPosjetu)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiPosjetu)
                        .addGap(177, 177, 177))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUvjetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUvjetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         ucitajPosjete();
        }
    }//GEN-LAST:event_txtUvjetKeyPressed

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
       ucitajPosjete();
    }//GEN-LAST:event_btnTraziActionPerformed

    private void btnDodajPosjetuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajPosjetuActionPerformed

        if(lstDogovorenePosjete.getSelectedValuesList()==null
            || lstDogovorenePosjete.getSelectedValuesList().isEmpty()){
            JOptionPane.showMessageDialog(getRootPane(),
                "Prvo pronađite posjetu");
            return;
        }

        if(lstPosjeteNaDjelatniku.getModel()==null ||
            !(lstPosjeteNaDjelatniku.getModel() instanceof DefaultListModel<Posjeta>)){
            lstPosjeteNaDjelatniku.setModel(new DefaultListModel<Posjeta>());
        }

        DefaultListModel<Posjeta> m =
        (DefaultListModel<Posjeta>) lstPosjeteNaDjelatniku.getModel();

        DefaultListModel<Posjeta> polaznici =
        (DefaultListModel<Posjeta>) lstPosjeteNaDjelatniku.getModel();
        boolean postoji;
        for(Posjeta pub : lstDogovorenePosjete.getSelectedValuesList()){
            postoji=false;
            for(int i=0;i<polaznici.getSize();i++){
                if(pub.getSifra()==polaznici.get(i).getSifra()){
                    postoji=true;
                    break;
                }
            }
            if(!postoji){
                polaznici.addElement(pub);
            }
        }
        lstPosjeteNaDjelatniku.repaint();

    }//GEN-LAST:event_btnDodajPosjetuActionPerformed

    private void btnObrisiPosjetuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiPosjetuActionPerformed
        if(lstPosjeteNaDjelatniku.getSelectedValuesList()==null
            || lstPosjeteNaDjelatniku.getSelectedValuesList().isEmpty()){
            JOptionPane.showMessageDialog(getRootPane(),
                "Prvo odaberite posjetu za uklanjanje sa djelatnika");
            return;
        }

        DefaultListModel<Posjeta> m =
        (DefaultListModel<Posjeta>) lstPosjeteNaDjelatniku.getModel();

        for(Posjeta p : lstPosjeteNaDjelatniku.getSelectedValuesList()){
            m.removeElement(p);
        }
        lstPosjeteNaDjelatniku.repaint();

    }//GEN-LAST:event_btnObrisiPosjetuActionPerformed

    private void cmbFilterDjelatniciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilterDjelatniciItemStateChanged
        ucitaj();
    }//GEN-LAST:event_cmbFilterDjelatniciItemStateChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
      Djelatnik d = (Djelatnik)cmbFilterDjelatnici.getSelectedItem();
       DefaultListModel<Posjeta> m=(DefaultListModel<Posjeta>) lstPosjeteNaDjelatniku.getModel();
       for( int i =0; i<m.getSize(); i++){
        m.get(i).setDjelatnik(d);
        obradaPosjeta.setEntitet(m.get(i));
           try {
               obradaPosjeta.update();
           } catch (Exception e) {
           }
      }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPregledPosjetaNaDjelatnikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledPosjetaNaDjelatnikuActionPerformed
        new ProzorPosjetePoZaposlenom().setVisible(true);
    }//GEN-LAST:event_btnPregledPosjetaNaDjelatnikuActionPerformed

    private void btnNoviUnos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviUnos1ActionPerformed
        new ProzorDjelatnik().setVisible(true);
    }//GEN-LAST:event_btnNoviUnos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajPosjetu;
    private javax.swing.JButton btnNoviUnos1;
    private javax.swing.JButton btnObrisiPosjetu;
    private javax.swing.JButton btnPregledPosjetaNaDjelatniku;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JComboBox<Djelatnik> cmbFilterDjelatnici;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Posjeta> lstDogovorenePosjete;
    private javax.swing.JList<Posjeta> lstPosjeteNaDjelatniku;
    private javax.swing.JTextField txtUvjet;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void napuniView() {
      
           var e = obradaDjelatnik.getEntitet();
         cmbFilterDjelatnici.setSelectedItem(e.getPosjete());
         
         
            DefaultListModel<Posjeta> m = new DefaultListModel<>();
        if(e.getPosjete()!=null){
            m.addAll(e.getPosjete());
        }
        lstPosjeteNaDjelatniku.setModel(m);
        lstPosjeteNaDjelatniku.repaint();
         
   }

    @Override
    public void napuniModel() {
       var e = obradaDjelatnik.getEntitet();
       
        cmbFilterDjelatnici.setSelectedItem(e.getIme());
          
     
         
    }
}
