/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package novoselac.view;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import novoselac.controller.ObradaDijete;
import novoselac.controller.ObradaPosjeta;
import novoselac.controller.ObradaUsluga;
import novoselac.model.Dijete;
import novoselac.model.Posjeta;
import novoselac.model.Usluga;
import novoselac.util.Aplikacija;

/**
 *
 * @author Administrator
 */
public class ProzorUslugaPosjeta 
        extends javax.swing.JFrame
implements NovoselacViewSucelje
{
 private ObradaPosjeta obrada;
    private ObradaUsluga obradaUsluga;
    /**
     * Creates new form ProzorUslugaPosjeta
     */
    public ProzorUslugaPosjeta() {
        initComponents();
          obrada = new ObradaPosjeta();
        obradaUsluga = new ObradaUsluga();
        
         setTitle(Aplikacija.NAZIV_NOVOSELAC+ ": "+
               Aplikacija.OPERATER.getImePrezime() +
                ": Pregled usluga po posjetama");
   ucitaj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPosjeta = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUsluga = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        dpPocetniDatum = new com.github.lgooddatepicker.components.DatePicker();
        dpKrajnjiDatum = new com.github.lgooddatepicker.components.DatePicker();
        btnPretraži = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Posjeta");

        lstPosjeta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPosjeta.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPosjetaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPosjeta);

        lstUsluga.setEnabled(false);
        jScrollPane2.setViewportView(lstUsluga);

        jLabel2.setText("Usluga");

        btnPretraži.setBackground(new java.awt.Color(37, 179, 213));
        btnPretraži.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPretraži.setForeground(new java.awt.Color(102, 102, 102));
        btnPretraži.setText("🔍");
        btnPretraži.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretražiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Do:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Od:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(dpPocetniDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dpKrajnjiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraži))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpPocetniDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dpKrajnjiDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPretraži)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPosjetaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPosjetaValueChanged
        if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstUsluga.getSelectedValue()==null){
            return;
        }

        obradaUsluga.setEntitet(lstUsluga.getSelectedValue());

        napuniView();
    }//GEN-LAST:event_lstPosjetaValueChanged

    private void btnPretražiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretražiActionPerformed
        if(dpPocetniDatum.getText().isEmpty() && dpKrajnjiDatum.getText().isEmpty()){
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite datum");

            return;
        }

        DefaultListModel<Posjeta> m = new DefaultListModel<>();
        //        m.addAll(obrada.read(dpPocetniDatum.getText(), dpKrajnjiDatum.getText()));

        lstPosjeta.setModel(m);
        lstPosjeta.repaint();
    }//GEN-LAST:event_btnPretražiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraži;
    private com.github.lgooddatepicker.components.DatePicker dpKrajnjiDatum;
    private com.github.lgooddatepicker.components.DatePicker dpPocetniDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Posjeta> lstPosjeta;
    private javax.swing.JList<Usluga> lstUsluga;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ucitaj() {
  DefaultListModel<Posjeta> m= new DefaultListModel<>();
//        m.addAll(obrada.read(txtUvjet.getText().trim()));
        lstPosjeta.setModel(m);
        lstPosjeta.repaint(); }

    @Override
    public void napuniView() {
  var u = obrada.getEntitet(); 
        DefaultListModel<Usluga> m = new DefaultListModel<>();
         m.addElement((Usluga) obradaUsluga.read());
        lstUsluga.setModel(m);
        lstUsluga.repaint();
    
    
    }

    @Override
    public void napuniModel() {
   var u = obrada.getEntitet(); }
}
