/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 
package novoselac.view;

import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import novoselac.controller.ObradaDijete;
import novoselac.controller.ObradaPosjeta;
import novoselac.controller.ObradaUsluga;
import novoselac.model.GrafPodaci;
import novoselac.model.Usluga;
import novoselac.util.Aplikacija;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.Dataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Administrator
 */
public class ProzorPregledUsluga 
        extends javax.swing.JFrame
implements NovoselacViewSucelje{
    
    private ObradaPosjeta obrada;
    private ObradaUsluga obradaUsluga;
    /**
     * Creates new form ProzorPregledUsluga
     */
    public ProzorPregledUsluga() {
        initComponents();
        obrada= new ObradaPosjeta();
        obradaUsluga= new ObradaUsluga();
        
        
         setTitle(Aplikacija.NAZIV_NOVOSELAC+ ": "+
               Aplikacija.OPERATER.getImePrezime() +
                ": Pregled broja pojeta po uslugama");
        definirajGraf();
    }
   

    
    
    private void definirajGraf(){
        
         DefaultPieDataset dataset = new DefaultPieDataset( );
         
         for(GrafPodaci gp : new ObradaUsluga().getGrafPodaci()){
            
             dataset.setValue(gp.getNaziv() + " (" + gp.getBroj() + ")", 
                     Double.valueOf(gp.getBroj()));
      }
         
         JFreeChart chart = ChartFactory.createPieChart(
         "Statistika usluga",   // naslov grafa
         dataset,          
         false,              
         false, 
         false);
          
          ChartPanel cp = new ChartPanel(chart);
          
          pnlGraf.setLayout(new BorderLayout());
          pnlGraf.add(cp,BorderLayout.CENTER);
          pnlGraf.validate();
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGraf = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlGrafLayout = new javax.swing.GroupLayout(pnlGraf);
        pnlGraf.setLayout(pnlGrafLayout);
        pnlGrafLayout.setHorizontalGroup(
            pnlGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        pnlGrafLayout.setVerticalGroup(
            pnlGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlGraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(pnlGraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlGraf;
    // End of variables declaration//GEN-END:variables
    @Override
    public void ucitaj() {
   }

    @Override
    public void napuniView() {
       
    
    }

    @Override
    public void napuniModel() {
     }
}
