/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package novoselac.view;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import novoselac.controller.ObradaDjelatnik;
import novoselac.controller.ObradaPosjeta;
import novoselac.model.Dijete;
import novoselac.model.Djelatnik;
import novoselac.model.Posjeta;
import novoselac.util.Aplikacija;

/**
 *
 * @author Administrator
 */
public class ProzorPregledPosjetaNaDjelatniku 
        extends javax.swing.JFrame 
        implements NovoselacViewSucelje{
    
    private ObradaPosjeta obrada;
    private ObradaDjelatnik obradaDjelatnik;
//     private DecimalFormat df;

    /**
     * Creates new form ProzorPregledPosjetaNaDjelatniku
     */
    public ProzorPregledPosjetaNaDjelatniku() {
        initComponents();
        obrada= new ObradaPosjeta();
        obradaDjelatnik = new ObradaDjelatnik();
//         DecimalFormatSymbols dfs=
//                new DecimalFormatSymbols(
//                        new Locale("hr", "HR"));
//        df= new DecimalFormat("###,##0.00", dfs);
        
         setTitle(Aplikacija.NAZIV_NOVOSELAC+ ": "+
               Aplikacija.OPERATER.getImePrezime() +
                ": Posjete na djelatniku");

         ucitaj();
    }
    public Posjeta getOdabranaPosjeta() {
        return lstDogovorenePosjete.getSelectedValue();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstDogovorenePosjete = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPodaci = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        lblBrojPosjetaNaDjelatniku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstDogovorenePosjete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDogovorenePosjeteMouseClicked(evt);
            }
        });
        lstDogovorenePosjete.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDogovorenePosjeteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstDogovorenePosjete);

        jLabel14.setText("Djelatnik");

        lstPodaci.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPodaci.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPodaciValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPodaci);

        jLabel15.setText("Posjeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblBrojPosjetaNaDjelatniku, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBrojPosjetaNaDjelatniku, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstDogovorenePosjeteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDogovorenePosjeteValueChanged
         if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstDogovorenePosjete.getSelectedValue()==null){
            return;
        }

        obrada.setEntitet(lstDogovorenePosjete.getSelectedValue());

        napuniView();
    }//GEN-LAST:event_lstDogovorenePosjeteValueChanged

    private void lstPodaciValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPodaciValueChanged
        if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstPodaci.getSelectedValue()==null){
            return;
        }

        obradaDjelatnik.setEntitet(lstPodaci.getSelectedValue());

        napuniView();
    }//GEN-LAST:event_lstPodaciValueChanged

    
    
    
    private void lstDogovorenePosjeteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDogovorenePosjeteMouseClicked
 new PodaciDjelatnikuInfoOOdabranojPosjeti().setVisible(true);
    }//GEN-LAST:event_lstDogovorenePosjeteMouseClicked

    @Override
    
    //veza posjete i djelatnika
    
    public void ucitaj() {
        DefaultListModel<Djelatnik> m=
                new DefaultListModel<>();
        m.addAll(obradaDjelatnik.read());
        lstPodaci.setModel(m);
    }

    @Override
    public void napuniView() {
         var d = obradaDjelatnik.getEntitet();
        
        // veza djelatnik posjeta       
        
   DefaultListModel<Posjeta> m = new DefaultListModel<>();
   if (d.getPosjete()!=null && !d.getPosjete().isEmpty()){
       m.addAll(d.getPosjete());
   }
   lstDogovorenePosjete.setModel(m);
   
   
  
   
   }

    @Override
    public void napuniModel() {
          var e = obradaDjelatnik.getEntitet();
         List<Posjeta> posjete = new ArrayList<>();
        try {
            DefaultListModel<Posjeta> m = (DefaultListModel<Posjeta>) lstDogovorenePosjete.getModel();
            for(int i=0;i<m.getSize();i++){
                posjete.add(m.getElementAt(i));
            }
        } catch (Exception ex) {
            
        }
        e.setPosjete(posjete);}

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrojPosjetaNaDjelatniku;
    private javax.swing.JList<Posjeta> lstDogovorenePosjete;
    private javax.swing.JList<Djelatnik> lstPodaci;
    // End of variables declaration//GEN-END:variables
}
